config/routes.rb
Rails.application.routes.draw do
  resources :posposts
  resources :users
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pospost.rb
class Pospost < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "hello, world!"
  end
end

app/controllers/posposts_controller.rb
class PospostsController < ApplicationController
  before_action :set_pospost, only: [:show, :edit, :update, :destroy]

  # GET /posposts
  # GET /posposts.json
  def index
    @posposts = Pospost.all
  end

  # GET /posposts/1
  # GET /posposts/1.json
  def show
  end

  # GET /posposts/new
  def new
    @pospost = Pospost.new
  end

  # GET /posposts/1/edit
  def edit
  end

  # POST /posposts
  # POST /posposts.json
  def create
    @pospost = Pospost.new(pospost_params)

    respond_to do |format|
      if @pospost.save
        format.html { redirect_to @pospost, notice: 'Pospost was successfully created.' }
        format.json { render :show, status: :created, location: @pospost }
      else
        format.html { render :new }
        format.json { render json: @pospost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posposts/1
  # PATCH/PUT /posposts/1.json
  def update
    respond_to do |format|
      if @pospost.update(pospost_params)
        format.html { redirect_to @pospost, notice: 'Pospost was successfully updated.' }
        format.json { render :show, status: :ok, location: @pospost }
      else
        format.html { render :edit }
        format.json { render json: @pospost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posposts/1
  # DELETE /posposts/1.json
  def destroy
    @pospost.destroy
    respond_to do |format|
      format.html { redirect_to posposts_url, notice: 'Pospost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pospost
      @pospost = Pospost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pospost_params
      params.require(:pospost).permit(:latitud, :longitud, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posposts_helper.rb
module PospostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posposts/_form.html.erb
<%= form_with(model: pospost, local: true) do |form| %>
  <% if pospost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pospost.errors.count, "error") %> prohibited this pospost from being saved:</h2>

      <ul>
      <% pospost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitud %>
    <%= form.text_field :latitud, id: :pospost_latitud %>
  </div>

  <div class="field">
    <%= form.label :longitud %>
    <%= form.text_field :longitud, id: :pospost_longitud %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :pospost_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posposts/edit.html.erb
<h1>Editing Pospost</h1>

<%= render 'form', pospost: @pospost %>

<%= link_to 'Show', @pospost %> |
<%= link_to 'Back', posposts_path %>

app/views/posposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posposts</h1>

<table>
  <thead>
    <tr>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posposts.each do |pospost| %>
      <tr>
        <td><%= pospost.latitud %></td>
        <td><%= pospost.longitud %></td>
        <td><%= pospost.user_id %></td>
        <td><%= link_to 'Show', pospost %></td>
        <td><%= link_to 'Edit', edit_pospost_path(pospost) %></td>
        <td><%= link_to 'Destroy', pospost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pospost', new_pospost_path %>

app/views/posposts/new.html.erb
<h1>New Pospost</h1>

<%= render 'form', pospost: @pospost %>

<%= link_to 'Back', posposts_path %>

app/views/posposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitud:</strong>
  <%= @pospost.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @pospost.longitud %>
</p>

<p>
  <strong>User:</strong>
  <%= @pospost.user_id %>
</p>

<%= link_to 'Edit', edit_pospost_path(@pospost) %> |
<%= link_to 'Back', posposts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>